story1/urls.py
from django.urls import re_path
from story1.views import index

urlpatterns = [
    re_path('^$', index, name='index'),
]

story8/urls.py
from django.urls import re_path, path
from story8.views import *

urlpatterns = [
    re_path(r'^$', index, name = 'index'),
    path('list-buku/', list_buku, name = 'api'),
]

story_ppw/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path, re_path
from django.shortcuts import reverse
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^story-1/', include(('story1.urls', 'story1'), namespace='story1')),
    url(r'^story-3/', include(('story3.urls', 'story3'), namespace='story3')),
    url(r'^story-5/', include(('story5.urls', 'story5'), namespace='story5')),
    url(r'^story-6/', include(('story6.urls', 'story6'), namespace='story6')),
    url(r'^story-7/', include(('story7.urls', 'story7'), namespace='story7')),
    url(r'^story-8/', include(('story8.urls', 'story8'), namespace='story8')),
    url(r'^story-9/', include(('story9.urls', 'story9'), namespace='story9')),
    re_path(r'^$', RedirectView.as_view(pattern_name='story9:index')),
]

story8/models.py
from django.db import models

# Create your models here.

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse

import json
import requests

def index(req):
    return render(req, 'story8/index.html')

def list_buku(req):
    query = req.GET.get('q', '')
    resp_json = {'totalItems': 0}
    if query != '':
        resp = requests.get(f'https://www.googleapis.com/books/v1/volumes?q={query}')
        resp_json = json.loads(resp.content.decode())
    return JsonResponse(resp_json)

templates/story8/index.html
{% extends '../base.html' %}

{% block title %}PPW Story 8 | Muhammad Faishol Amirul Mukminin{% endblock %}

{% block contents %}
<main role="main" class="container">
    <h1 class="font-mono mb-5" style="text-align: center;">Story 8</h1>
    <div class="input-group mb-3">
        <input id="search-input" type="text" class="form-control" placeholder="Search keyword...">
        <div class="input-group-append">
          <button id="search-button" class="input-group-text" id="basic-addon1">
            <svg style="width:20px" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="search" class="svg-inline--fa fa-search fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M505 442.7L405.3 343c-4.5-4.5-10.6-7-17-7H372c27.6-35.3 44-79.7 44-128C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c48.3 0 92.7-16.4 128-44v16.3c0 6.4 2.5 12.5 7 17l99.7 99.7c9.4 9.4 24.6 9.4 33.9 0l28.3-28.3c9.4-9.4 9.4-24.6.1-34zM208 336c-70.7 0-128-57.2-128-128 0-70.7 57.2-128 128-128 70.7 0 128 57.2 128 128 0 70.7-57.2 128-128 128z"></path></svg>
          </button>
        </div>
    </div>
    <div id="search-result" class="row">
    </div>
</main>
{% endblock %}

{% block customjs %}
<script>
    function parseElement(elm) {
        let image = elm['volumeInfo']['imageLinks']['thumbnail'];
        let infoLink = elm['volumeInfo']['infoLink'];
        let title = elm['volumeInfo']['title'];

        let authors = elm['volumeInfo']['authors'];
        let authors_str = "Unknown";
        if (authors != null) {
            authors_str = authors.join(', ');
        }

        let desc = 'No description';
        if (elm['volumeInfo']['description'] != null) {
            desc = elm['volumeInfo']['description'];
            if (desc.length > 300){
                desc = desc.slice(0, 300) + "...";
            }
        }
        
        let html = `<div class='search-item col-12 row'>
            <div class='col-1'>
                <img src='${image}' height=80/>
            </div>
            <div class='col-11'>
                <h5 class='mb-0'><a href='${infoLink}'>${title}</a></h5>
                <small>by ${authors_str}</small>
                <p class='mt-2'>${desc}</p>
            </div>
            <div class='col-12'><hr></div>
        </div>`;
        $('#search-result').append(html);
    }
    

    function getAPI() {
        $('.search-item').remove();
        let load_html = `<div class='search-item text-center col-12'><div class="spinner-border text-primary" role="status"><span class="sr-only">Loading...</span></div></div>`;
        $("#search-result").append(load_html);

        let keyword = $('#search-input').val();
        $.getJSON(`{% url 'story8:api' %}?q=${keyword}`, (data) => {
            $('.search-item').remove();
            
            let numData = data['totalItems'];
            if (numData == 0) {
                $("#search-result").append(`<div class='search-item text-center col-12'>No results found</div>`);
            } else {
                data['items'].forEach(parseElement);
            }
        });
    }
    
    $('#search-input').keyup((e) => {
        if(e.keyCode == 13) getAPI();
    });
    $('#search-button').click(getAPI);
</script>
{% endblock %}