story1/urls.py
from django.urls import re_path
from story1.views import index

urlpatterns = [
    re_path('^$', index, name='index'),
]

story5/urls.py
from django.urls import re_path, path
from story5.views import index, view_course, add_course, del_course

urlpatterns = [
    re_path('^$', index, name = 'index'),
    path('<int:courseid>/view/', view_course),
    path('add/', add_course),
    path('<int:courseid>/delete/', del_course)
]

story_ppw/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path, re_path
from django.shortcuts import reverse
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^story-1/', include(('story1.urls', 'story1'), namespace='story1')),
    url(r'^story-3/', include(('story3.urls', 'story3'), namespace='story3')),
    url(r'^story-5/', include(('story5.urls', 'story5'), namespace='story5')),
    url(r'^story-6/', include(('story6.urls', 'story6'), namespace='story6')),
    url(r'^story-7/', include(('story7.urls', 'story7'), namespace='story7')),
    url(r'^story-8/', include(('story8.urls', 'story8'), namespace='story8')),
    url(r'^story-9/', include(('story9.urls', 'story9'), namespace='story9')),
    re_path(r'^$', RedirectView.as_view(pattern_name='story9:index')),
]

story5/models.py
from django.db import models

class Course(models.Model):
    name = models.CharField(max_length = 100)
    lecturer = models.CharField(max_length = 100)
    sks = models.IntegerField()
    description = models.TextField(blank=True)
    term = models.CharField(max_length=50)
    room = models.CharField(max_length=50)

story5/forms.py
from django import forms

class CourseForm(forms.Form):
    nama_mata_kuliah = forms.CharField(max_length=100)
    jumlah_sks = forms.IntegerField()
    dosen = forms.CharField(max_length=100, widget=forms.Textarea)
    semester_tahun = forms.CharField(max_length=50)
    ruang_kelas = forms.CharField(max_length=50)
    deskripsi = forms.CharField(widget=forms.Textarea, required=False)

story5/views.py
from django.shortcuts import render, redirect
from story5.models import Course
from story5.forms import CourseForm

def index(request):
    context = {
        'courses': Course.objects.all(),
        'form': CourseForm()
    }
    return render(request, 'story5/index.html', context)

def view_course(request, courseid):
    try:
        context = {
            'course': Course.objects.get(id = courseid)
        }
        return render(request, 'story5/detail_course.html', context)
    except:
        return redirect('/story-5/')

def add_course(request):
    if request.method == "POST":
        form = CourseForm(request.POST)
        if form.is_valid():
            new_course = Course()
            new_course.name = form.cleaned_data['nama_mata_kuliah']
            new_course.lecturer = form.cleaned_data['dosen']
            new_course.sks = form.cleaned_data['jumlah_sks']
            new_course.description = form.cleaned_data['deskripsi']
            new_course.term = form.cleaned_data['semester_tahun']
            new_course.room = form.cleaned_data['ruang_kelas']
            new_course.save()
    return redirect('/story-5/')

def del_course(request, courseid):
    Course.objects.filter(id = courseid).delete()
    return redirect('/story-5/')

templates/story5/detail_course.html
{% extends '../base.html' %}

{% block title %}PPW Story 5 | Muhammad Faishol Amirul Mukminin{% endblock %}
{% block contents %}
<main role="main" class="container">
    <h1 class="font-mono mb-5" style="text-align: center;">Info Mata Kuliah</h1>
    <div class="row">
        <div class="col-md-4">
            <h5><strong>Nama Mata Kuliah</strong></h5>
            <p>{{ course.name }}</p>
            <h5><strong>SKS</strong></h5>
            <p>{{ course.sks }}</p>
        </div>
        <div class="col-md-4">
            <h5><strong>Semester Tahun</strong></h5>
            <p>{{ course.term }}</p>
            <h5><strong>Ruangan</strong></h5>
            <p>{{ course.room }}</p>
        </div>
        <div class="col-md-4">
            <h5><strong>Dosen Pengajar</strong></h5>
            <p>{{ course.lecturer }}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <h5><strong>Deskripsi</strong></h5>
            <p>{{ course.description }}</p>
        </div>
    </div>
    <div class="row mt-5">
        <a href="/story-5/" class="btn btn-primary">Kembali</a>
    </div>
</main>
{% endblock %}

templates/story5/index.html
{% extends '../base.html' %}

{% block title %}PPW Story 5 | Muhammad Faishol Amirul Mukminin{% endblock %}
{% block contents %}
<main role="main" class="container">
    <h1 class="font-mono mb-5" style="text-align: center;">Tambah Mata Kuliah</h1>
    <form action="/story-5/add" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_nama_mata_kuliah">Nama mata kuliah:</label>
            <input type="text" class="form-control" name="nama_mata_kuliah" maxlength="100" required="" id="id_nama_mata_kuliah">
        </div>
        <div class="form-group">
            <label for="id_jumlah_sks">Jumlah sks:</label>
            <input type="number" class="form-control" name="jumlah_sks" required="" id="id_jumlah_sks">
        </div>
        <div class="form-group">
            <label for="id_dosen">Dosen:</label>
            <textarea name="dosen" class="form-control" cols="40" rows="5" maxlength="100" required="" id="id_dosen"></textarea>
        
        </div>
        <div class="form-group">
            <label for="id_semester_tahun">Semester tahun:</label>
            <input type="text" class="form-control" name="semester_tahun" maxlength="50" required="" id="id_semester_tahun">
        </div>
        <div class="form-group">
            <label for="id_ruang_kelas">Ruang kelas:</label>
            <input type="text" class="form-control" name="ruang_kelas" maxlength="50" required="" id="id_ruang_kelas">        
        </div>
        <div class="form-group">
            <label for="id_deskripsi">Deskripsi:</label>
            <textarea name="deskripsi" class="form-control" cols="40" rows="5" id="id_deskripsi"></textarea>
        </div>
        <button class="btn btn-primary" value="Submit">Submit</button>
    </form>
    <h1 class="font-mono mb-5" style="text-align: center;">Daftar Mata Kuliah</h1>
    <table class="table">
        <tr>
            <th>Nama Mata Kuliah</th>
            <th>Semester Tahun</th>
            <th>Pengajar</th>
            <th></th>
        </tr>
        {% for course in courses %}
        <tr>
            <td>{{ course.name }}</td>
            <td>{{ course.term }}</td>
            <td>{{ course.lecturer }}</td>
            <td>
                <a href="/story-5/{{ course.id }}/view" class="btn btn-primary">view</a>
                <a href="/story-5/{{ course.id }}/delete" class="btn btn-danger">delete</a>
            </td>
        </tr>
        {% endfor %}
    </table>
    
</main>
{% endblock %}