story1/urls.py
from django.urls import re_path
from story1.views import index

urlpatterns = [
    re_path('^$', index, name='index'),
]

story_ppw/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path, re_path
from django.shortcuts import reverse
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^story-1/', include(('story1.urls', 'story1'), namespace='story1')),
    url(r'^story-3/', include(('story3.urls', 'story3'), namespace='story3')),
    url(r'^story-5/', include(('story5.urls', 'story5'), namespace='story5')),
    url(r'^story-6/', include(('story6.urls', 'story6'), namespace='story6')),
    url(r'^story-7/', include(('story7.urls', 'story7'), namespace='story7')),
    url(r'^story-8/', include(('story8.urls', 'story8'), namespace='story8')),
    url(r'^story-9/', include(('story9.urls', 'story9'), namespace='story9')),
    re_path(r'^$', RedirectView.as_view(pattern_name='story9:index')),
]

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=VT323&display=swap" rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>
    <style>
      body {
        min-height: 80rem;
        padding-top: 6.5rem;
        background-color: #F9F9F9;
      }
      .bg-maroon {
        background-color: #9D0208;
      }
      .font-mono {
        font-family: VT323, monospace;
      }
    </style>
    {% block customcss %}{% endblock %}
  </head>
  <body>
    {% include './navbar.html' %}
    {% block contents %}{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script>
      function getActiveNavbar() {
        let nowURL = window.location.pathname;
        let menuActive = "#" + nowURL.slice(nowURL.indexOf('/') + 1, nowURL.indexOf('/',1)) + "-navbar";
        $(menuActive).addClass('active');
      }
      $(document).ready(getActiveNavbar);
    </script>
    {% block customjs %}{% endblock %}
  </body>
</html>

templates/navbar.html
{% load static %}
<nav id="main-navbar" class="navbar navbar-expand-md navbar-dark fixed-top bg-maroon font-mono">
  <a class="navbar-brand ml-5" href="/" style="font-size:32px">
    <img src="{% static "logo-white.png" %}" alt="logo" width=30/>
    FAISHOL
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse" style="font-size:24px">
    <ul class="navbar-nav mr-auto">
      <li id="story-1-navbar" class="nav-item">
        <a class="nav-link" href="{% url 'story1:index' %}">Story 1</a>
      </li>
      <li id="story-3-navbar" class="nav-item">
        <a class="nav-link" href="{% url 'story3:index' %}">Story 3</a>
      </li>
      <li id="story-5-navbar" class="nav-item">
        <a class="nav-link" href="{% url 'story5:index' %}">Story 5</a>
      </li>
      <li id="story-6-navbar" class="nav-item">
        <a class="nav-link" href="{% url 'story6:index' %}">Story 6</a>
      </li>
      <li id="story-7-navbar" class="nav-item">
        <a class="nav-link" href="{% url 'story7:index' %}">Story 7</a>
      </li>
      <li id="story-8-navbar" class="nav-item">
        <a class="nav-link" href="{% url 'story8:index' %}">Story 8</a>
      </li>
      <li id="story-9-navbar" class="nav-item">
        <a class="nav-link" href="{% url 'story9:index' %}">Story 9</a>
      </li>
    </ul>
    <ul class="navbar-nav mr-5">
      {% for menu in custom_menu %}
        <li class="nav-item {% if menu.active %} active {% endif %}">
          <a class="nav-link" href="{{ menu.url }}">{{ menu.text }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
</nav>