story1/urls.py
from django.urls import re_path
from story1.views import index

urlpatterns = [
    re_path('^$', index, name='index'),
]

story6/urls.py
from django.urls import re_path, path
from story6.views import *
from django.shortcuts import reverse
from django.views.generic import RedirectView

urlpatterns = [
    re_path(r'^$', RedirectView.as_view(pattern_name = 'story6:index')),
    re_path(r'^activities/$', index, name = 'index'),
    path('activities/add/', add_activity, name = 'add_activity'),
    path('activities/<int:code>/add_participant/', add_participant, name = 'add_participant'),
]

story_ppw/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path, re_path
from django.shortcuts import reverse
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^story-1/', include(('story1.urls', 'story1'), namespace='story1')),
    url(r'^story-3/', include(('story3.urls', 'story3'), namespace='story3')),
    url(r'^story-5/', include(('story5.urls', 'story5'), namespace='story5')),
    url(r'^story-6/', include(('story6.urls', 'story6'), namespace='story6')),
    url(r'^story-7/', include(('story7.urls', 'story7'), namespace='story7')),
    url(r'^story-8/', include(('story8.urls', 'story8'), namespace='story8')),
    url(r'^story-9/', include(('story9.urls', 'story9'), namespace='story9')),
    re_path(r'^$', RedirectView.as_view(pattern_name='story9:index')),
]

story6/models.py
from django.db import models

class Activity(models.Model):
    title = models.CharField(max_length = 50)

class Participant(models.Model):
    name = models.CharField(max_length = 50)
    activity = models.ForeignKey(Activity, on_delete = models.CASCADE)

story5/forms.py
from django import forms

class CourseForm(forms.Form):
    nama_mata_kuliah = forms.CharField(max_length=100)
    jumlah_sks = forms.IntegerField()
    dosen = forms.CharField(max_length=100, widget=forms.Textarea)
    semester_tahun = forms.CharField(max_length=50)
    ruang_kelas = forms.CharField(max_length=50)
    deskripsi = forms.CharField(widget=forms.Textarea, required=False)

story6/views.py
from django.shortcuts import render, redirect, reverse
from story6.models import Activity, Participant

def index(req):
    context = {
        "activities": []
    }

    activities = Activity.objects.all()
    for activ in activities:
        peserta = Participant.objects.filter(activity = activ.pk)
        context['activities'].append({
            'title': activ.title,
            'id': activ.pk,
            'participants': peserta
        })
    return render(req, 'story6/index.html', context = context)

def add_activity(req):
    try:
        if req.method == "POST":
            title = req.POST['nama_kegiatan']
            if len(title) < 50:
                Activity.objects.create(title = title)
    finally:
        return redirect(reverse('story6:index'))
    
def add_participant(req, code):
    context = dict()
    try:
        context["activity"] = Activity.objects.get(pk = code) 
        try:
            if req.method == "POST":
                nama = req.POST['nama_peserta']
                if len(nama) < 50:
                    Participant.objects.create(name = nama, activity = Activity.objects.get(pk = code))
        finally:
            return render(req, 'story6/add_participant.html', context = context)
    except Activity.DoesNotExist:
        return redirect(reverse('story6:index'))

templates/story6/add_participant.html
{% extends '../base.html' %}

{% block title %}PPW Story 6 | Muhammad Faishol Amirul Mukminin{% endblock %}

{% block contents %}
<main role="main" class="container">
    <h1 class="font-mono mb-5" style="text-align: center;">{{ activity.title }}</h1>
    <form action="{% url 'story6:add_participant' activity.pk %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_nama_mata_kuliah">Nama Peserta:</label>
            <input type="text" class="form-control" name="nama_peserta" maxlength="50" required="">
        </div>
        <button class="btn btn-primary" value="Submit">Tambah</button>
        <a href="{% url 'story6:index' %}" class="btn btn-danger">Kembali</a>
    </form>
</main>
{% endblock %}

templates/story6/index.html
{% extends '../base.html' %}

{% block title %}PPW Story 6 | Muhammad Faishol Amirul Mukminin{% endblock %}

{% block contents %}
<main role="main" class="container">
    <h1 class="font-mono mb-5" style="text-align: center;">Tambah Kegiatan</h1>
    <form action="{% url 'story6:add_activity' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_nama_mata_kuliah">Nama Kegiatan:</label>
            <input type="text" class="form-control" name="nama_kegiatan" maxlength="50" required="">
        </div>
        <button class="btn btn-primary" value="Submit">Submit</button>
    </form>
    <h1 class="font-mono mb-5" style="text-align: center;">Daftar Kegiatan</h1>
    <table class="table">
        <tr>
            <th>Nama Kegiatan</th>
            <th>Daftar Peserta</th>
            <th></th>
        </tr>
        {% for activ in activities %}
        <tr>
            <td>{{ activ.title }}</td>
            <td>
                <ul>
                    {% for p in activ.participants %}
                        <li>{{ p.name }}</li>
                    {% endfor %}
                </ul>
            </td>
            <td>
                <a href="{% url 'story6:add_participant' activ.id %}" class="btn btn-primary">Tambah Peserta</a>
            </td>
        </tr>
        {% endfor %}
    </table>
</main>
{% endblock %}